### ISSUE TITLE
无法运行INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113.

### ISSUE THREAD

**Issue by hloong** [uncleleonfan/FunWallet#1]
如下图，已经尝试了下面博文的几种方法都无效

解决方案
检查\app\src\main\AndroidMainfest.xml中是否有testOnly属性为true，如果有去掉或者改为false
检查Android Studio和gradle版本是否为alpha版本，换为稳定版本
检查是否关闭Instant Run功能，关掉此功能
检查是否使用alpha版本的依赖库，换成稳定版本
如果以上均无法解决，就在gradle.properties文件中添加android.injected.testOnly=false

--------------------- 
作者：Donkor- 
来源：CSDN 
原文：https://blog.csdn.net/donkor_/article/details/82251888 
版权声明：本文为博主原创文章，转载请附上博文链接！
----

还有尝试
在app目录中找到build.gradle，然后在Android节点下添加如下代码：
```
splits {  
   abi {  
            enable true  
            reset()  
            include 'x86', 'arm64-v8a', 'armeabi-v7a', 'x86_64'  
            universalApk true  
         } 
  }
```
--------------------- 
作者：都夕楠之 
来源：CSDN 
原文：https://blog.csdn.net/b1015222035/article/details/70231527 
版权声明：本文为博主原创文章，转载请附上博文链接！

以上都无法解决问题，项目无法运行（AS 3.2.1版本，java1.8，grade v4.6）
![image](https://user-images.githubusercontent.com/3353954/51817336-399e6000-2305-11e9-8b10-b7889f9b2407.png)

Installation failed with message Failed to finalize session : INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?

**Comment by Jokerchao** [comment]
查询资料后，在build.gradle中添加以下代码解决问题：
  packagingOptions {
        exclude 'lib/x86_64/darwin/libscrypt.dylib'
        exclude 'lib/x86_64/freebsd/libscrypt.so'
        exclude 'lib/x86_64/linux/libscrypt.so'
    }
